### ISSUE TITLE
New / Edit Locations-> Save & Continue Edit Fails

### ISSUE THREAD

**Issue by MattDunbar** [DemacMedia/Magento-Multi-Location-Inventory#22]
Returns js error:
Uncaught ReferenceError: saveAndContinueEdit is not defined

**Comment by dmanners** [comment]
Fix is included in https://github.com/DemacMedia/Magento-Multi-Location-Inventory/pull/44

See commit: https://github.com/DemacMedia/Magento-Multi-Location-Inventory/pull/44/commits/48882c8bce61ff7bf064e3af1d2e110a31ea0d78
