### ISSUE TITLE
Single Location used every time for qty reduction when order placed.

### ISSUE THREAD

**Issue by igniters1** [DemacMedia/Magento-Multi-Location-Inventory#30]
Using Magento Community 1.9.1.0

I have created different locations for different store views and assigned different qty for different locations.
When I placed order for Store View #2, which should deduct qty from its assgined location #2.
but it didnt deduct qty from Location #2. It always deduct qty from Location #1.

**Comment by dvdsndr** [comment]
see the bug I noted
