### ISSUE TITLE
Configurable product stock status not updated by stored procedure

### ISSUE THREAD

**Issue by jharrisonau** [DemacMedia/Magento-Multi-Location-Inventory#32]
When a configurable product has a stock_status of 0 but all child products are in stock, the stored procedure fails to update the stock_status back to 1. I found that running the configurable product SELECT statements by themselves works fine but when the simple+giftcard SELECT statements are UNIONed it stops working.

I think it's something to do with the wrong product_id field being used in some spots or possibly the order of the fields being selected. I'll submit a pull request when I solve it.

**Comment by navitelia** [comment]
Yes,, thats correct I am currently experience this issue.

Is there a temporary solution?

Thanks

**Comment by jharrisonau** [comment]
I've added a fix for this to my fork, see here:
https://github.com/arkadedigital/Demac-Multi-Location-Inventory-Magento-Module/tree/develop

**Comment by navitelia** [comment]
I am having the same issue with configurables, I tried manage stock no, put
1000 stock but nothing.. I have no way to display the configurable IN Stock
(regardless the amount of associates IN STOCK)

Import its full working, thanks!

**Comment by amacgregor** [comment]
jharrisonau I'm taking a look at your pull request.

**Comment by WJdeBaas** [comment]
I've found the issue, according to the MySql manual:
http://dev.mysql.com/doc/refman/5.7/en/union.html

> The column names from the first SELECT statement are used as the column names for the results returned. Selected columns listed in corresponding positions of each SELECT statement should have the same data type. (For example, the first column selected by the first statement should have the same type as the first column selected by the other statements.)

The sequence of the selected fields where configurables are indexed are different from the other, eg:
Fields of the first select are
1. **product_id**,
2. qty, 
3. is_in_stock,
4. backorders, 
5. manage_stock, 
6. store_id

The fields for the configurable are
1. **store_id**,
2. product_id,
3. qty,
4. is_in_stock,
5. backorders,
6. manage_stock

I'll try to attach another install script with the fix in it, just change the version numbers to your situation.


[upgrade-1.2.5.1-1.2.5.2.php.zip](https://github.com/DemacMedia/Magento-Multi-Location-Inventory/files/204546/upgrade-1.2.5.1-1.2.5.2.php.zip)

**Comment by paras89** [comment]
Is there an update to this?

I have also found that there is a mismatch in the column orders of the various selects in the stored procedure.

Going to have a look at the upgrade script to above to see if the change in procedure helps.

**Comment by demac-rd** [comment]
Thanks to David for providing a fix for this issue.
